# -*- coding: utf-8 -*-
"""email_cleaner.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXptYuvrpDz2WRBpIwhXUyD2XlKkUUze
"""

import pandas as pd
import re


df = pd.read_csv("leads.csv")


df.columns = df.columns.str.strip()


df = df.dropna(subset=["Email"])


def is_valid_email(email):
    return bool(re.match(r"[^@]+@[^@]+\.[^@]+", str(email)))

df = df[df["Email"].apply(is_valid_email)]


df = df.drop_duplicates(subset=["Email"])


df.to_csv("cleaned_leads.csv", index=False)

print("Cleaned data saved as cleaned_leads.csv")

